# Generated by Django 2.0.3 on 2018-04-18 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=60)),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('todo_create_date', models.DateTimeField(verbose_name='date todo created')),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todolist_text', models.CharField(max_length=60)),
                ('list_create_date', models.DateTimeField(verbose_name='date list created')),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='todolist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.ToDoList'),
        ),
    ]
