# Generated by Django 2.0.3 on 2018-04-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_create_date',
            field=models.DateField(verbose_name='date todo created'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='list_create_date',
            field=models.DateField(verbose_name='date list created'),
        ),
    ]
