# Generated by Django 2.0.3 on 2018-04-18 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20180418_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_create_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='list_create_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date created'),
        ),
    ]
