# Generated by Django 2.0.3 on 2018-04-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20180418_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='num_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todolist',
            name='num_completed',
            field=models.IntegerField(default=0),
        ),
    ]
