# Generated by Django 2.0.3 on 2018-04-18 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20180418_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='latest_deadline',
            field=models.DateField(default=datetime.date.today, verbose_name='latest deadline'),
        ),
    ]
