# Generated by Django 2.0.3 on 2018-04-21 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todolist_latest_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='latest_deadline',
            field=models.DateField(default=datetime.date(2099, 12, 30), verbose_name='latest deadline'),
        ),
    ]
